Update README.md
Added a color prop when using Linegraph Component. The reason for updating the documentation is that I encountered an error when I was following it when developing using Expo Go. 
Error: [TypeError: undefined is not an object (evaluating 'color.startsWith')]
Solution: I added a color prop to Linegraph Component but that was not mentioned in the documentation.